using System.ComponentModel;
using Terraria.ModLoader.Config;

namespace 可成长的孔雀翎
{
    public enum ParticleEffectLevel
    {
        [Label("极简 (流畅优先) / Low")] Low,
        [Label("均衡 (推荐设置) / Medium")] Medium,
        [Label("全开 (画质优先) / High")] High
    }

    public enum MalachiteLanguage
    {
        [Label("简体中文")] Chinese,
        [Label("English")] English
    }

    public class MalachiteConfig : ModConfig
    {
        public override ConfigScope Mode => ConfigScope.ClientSide;

        [Header("Localization_语言设置")]
        [Label("Mod Language / 模组语言")]
        [Tooltip("Switch the language of Malachite's custom texts.\n切换对话与星图的语言。")]
        [DefaultValue(MalachiteLanguage.Chinese)]
        [DrawTicks]
        public MalachiteLanguage Language;

        [Header("Performance_性能与画质")]
        [Label("Particle Density / 粒子特效密度")]
        [Tooltip("Controls the number of particles generated by attacks, crits, and swords.\n控制攻击、暴击、剑阵自转等产生的粒子数量。\n极简：大幅砍掉次要特效，解决卡顿。\n均衡：动态限制特效，兼顾画质与帧数。\n全开：不做任何限制。")]
        [DefaultValue(ParticleEffectLevel.Medium)]
        [DrawTicks]
        public ParticleEffectLevel ParticleLevel;

        [Header("UI_界面设置")]
        [Label("Auto Play Dialog / 自动播放对话")]
        [Tooltip("When enabled, dialogues will play automatically. When disabled, you need to click the dialog box to proceed.\n开启时对话将自动播放，关闭时需要点击对话框才能进入下一句。")]
        [DefaultValue(true)]
        public bool AutoPlayDialog;
    }
}
